const translations = {
    'ru': {
        'title': 'АСТРО<br>УБОРЩИК',
        'btn_select_sector': 'ВЫБРАТЬ СЕКТОР',
        'btn_hangar': 'АНГАР КОРАБЛЕЙ',
        'btn_how_to_play': 'КАК ИГРАТЬ',
        'how_to_play_title': 'КАК ИГРАТЬ',
        'how_to_1': '🚀 Управляй кораблем мышкой или касанием.',
        'how_to_2': '🗑️ Собирай космический мусор (подлетай близко).',
        'how_to_3': '💰 Сдавай мусор на зеленую Базу, чтобы получить монеты.',
        'how_to_4': '🛒 Прокачивай корабль во внутриигровом Магазине (клавиша <b>M</b> или <b>Ь</b>).',
        'how_to_5': '⚠️ Остерегайся пиратов и астероидов!',
        'btn_back': 'Назад в меню',
        'hangar_title': 'АНГАР КОРАБЛЕЙ',
        'bank': 'Банк: ',
        'map_title': 'КАРТА СЕКТОРОВ',
        'defenders': '🛡️ Защитники: ',
        'cargo': '📦 Трюм: ',
        'sector': 'Сектор: ',
        'trash': 'Мусор: ',
        'thrust': 'Тяга: ',
        'in_run': '💰 В вылазке: ',
        'btn_shop': '🛒 МАГАЗИН',
        'shop_title': 'ОРБИТАЛЬНАЯ СТАНЦИЯ',
        'shop_drone': 'Защитник',
        'shop_drone_desc': 'Летает по орбите, уничтожает 1 пирата.',
        'shop_hp': 'Сплав Корпуса',
        'shop_hp_desc': 'Увеличивает максимальный запас прочности (HP).',
        'shop_profit': 'Улучшенный Сканер',
        'shop_profit_desc': 'Множитель прибыли: мусор стоит дороже.',
        'shop_cap': 'Отсек Трюма',
        'shop_cap_desc': 'Вмещает больше мусора за рейс.',
        'shop_magnet': 'Электромагнит',
        'shop_magnet_desc': 'Увеличивает радиус захвата мусора.',
        'shop_speed': 'Двигатель',
        'shop_speed_desc': 'Увеличивает базовую скорость полета НЛО.',
        'btn_buy': 'Купить (200)',
        'btn_upgrade': 'Улучшить',
        'btn_close_shop': 'Вернуться в космос',
        'overlay_win': 'СЕКТОР ЗАЧИЩЕН',
        'overlay_win_desc': 'Вы собрали весь мусор!',
        'btn_to_sectors': 'В меню секторов',
        'overlay_lose': 'КОРАБЛЬ РАЗРУШЕН',
        'overlay_lose_desc': 'Вас подбили пираты. Восстановить корабль за рекламу?',
        'btn_revive': 'Воскреснуть (Реклама)',
        'btn_reject': 'Отказаться',
        'tut_1': 'Управляй кораблем и собирай мусор!',
        'tut_2': 'Отвези мусор на Базу (зеленая зона)',
        'tut_3': 'Открой Магазин и улучши свой корабль!',
        'max_lvl': '(Макс)',
        'locked': 'Закрыто',
        'equip': 'Выбрать',
        'equipped': 'Выбран',
        'buy_ship': 'Купить',
        'float_shield': 'ЩИТ СРАБОТАЛ!',
        'stats_hp': 'Броня: ',
        'stats_speed': 'Скорость: ',
        'stats_cap': 'Вместимость: ',
        'stats_mag': 'Магнит: ',
        'stats_prof': 'Прибыль: x'
    },
    'en': {
        'title': 'ASTRO<br>CLEANER',
        'btn_select_sector': 'SELECT SECTOR',
        'btn_hangar': 'SHIP HANGAR',
        'btn_how_to_play': 'HOW TO PLAY',
        'how_to_play_title': 'HOW TO PLAY',
        'how_to_1': '🚀 Control the ship with mouse or touch.',
        'how_to_2': '🗑️ Collect space debris (fly close).',
        'how_to_3': '💰 Deliver debris to the green Base to get coins.',
        'how_to_4': '🛒 Upgrade your ship in the Shop (<b>M</b> key).',
        'how_to_5': '⚠️ Beware of pirates and asteroids!',
        'btn_back': 'Back to menu',
        'hangar_title': 'SHIP HANGAR',
        'bank': 'Bank: ',
        'map_title': 'SECTOR MAP',
        'defenders': '🛡️ Defenders: ',
        'cargo': '📦 Cargo: ',
        'sector': 'Sector: ',
        'trash': 'Debris: ',
        'thrust': 'Thrust: ',
        'in_run': '💰 Current Run: ',
        'btn_shop': '🛒 SHOP',
        'shop_title': 'ORBITAL STATION',
        'shop_drone': 'Defender',
        'shop_drone_desc': 'Flies in orbit, destroys 1 pirate.',
        'shop_hp': 'Hull Alloy',
        'shop_hp_desc': 'Increases maximum health (HP).',
        'shop_profit': 'Advanced Scanner',
        'shop_profit_desc': 'Profit multiplier: debris costs more.',
        'shop_cap': 'Cargo Hold',
        'shop_cap_desc': 'Holds more debris per trip.',
        'shop_magnet': 'Electromagnet',
        'shop_magnet_desc': 'Increases debris attraction radius.',
        'shop_speed': 'Engine',
        'shop_speed_desc': 'Increases base UFO flight speed.',
        'btn_buy': 'Buy (200)',
        'btn_upgrade': 'Upgrade',
        'btn_close_shop': 'Return to space',
        'overlay_win': 'SECTOR CLEARED',
        'overlay_win_desc': 'You collected all debris!',
        'btn_to_sectors': 'To sector menu',
        'overlay_lose': 'SHIP DESTROYED',
        'overlay_lose_desc': 'You were hit by pirates. Restore ship for an ad?',
        'btn_revive': 'Revive (Ad)',
        'btn_reject': 'Give Up',
        'tut_1': 'Control the ship and collect debris!',
        'tut_2': 'Deliver debris to the Base (green zone)',
        'tut_3': 'Open Shop and upgrade your ship!',
        'max_lvl': '(Max)',
        'locked': 'Locked',
        'equip': 'Equip',
        'equipped': 'Equipped',
        'buy_ship': 'Buy',
        'float_shield': 'SHIELD ACTIVE!',
        'stats_hp': 'Armor: ',
        'stats_speed': 'Speed: ',
        'stats_cap': 'Capacity: ',
        'stats_mag': 'Magnet: ',
        'stats_prof': 'Profit: x'
    }
};

window.lang = 'ru';
function t(key) {
    return translations[window.lang][key] || key;
}
